# k8s/common/postgres-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: mlops-proyecto3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        fsGroup: 999  # el GID por defecto de postgres en la imagen alpine
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
          - name: POSTGRES_USER
            value: "mlflow"
          - name: POSTGRES_PASSWORD
            value: "mlflow"
          - name: POSTGRES_DB
            value: "mlflow"
        ports:
          - containerPort: 5432
        volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/data
        resources:
          requests:
            cpu:    "0.25"
            memory: "256Mi"
          limits:
            cpu:    "0.5"
            memory: "512Mi"
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: mlflow-postgres-pvc
