# k8s/common/postgres-airflow-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-airflow
  namespace: mlops-proyecto3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-airflow
  template:
    metadata:
      labels:
        app: postgres-airflow
    spec:
      securityContext:
        fsGroup: 999
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
          - name: POSTGRES_USER
            value: "airflow"
          - name: POSTGRES_PASSWORD
            value: "airflow"
          - name: POSTGRES_DB
            value: "airflow"
        ports:
          - containerPort: 5432
        volumeMounts:
          - name: airflow-postgres-storage
            mountPath: /var/lib/postgresql/data
        resources:
          requests:
            cpu:    "0.25"
            memory: "256Mi"
          limits:
            cpu:    "0.5"
            memory: "512Mi"
      volumes:
        - name: airflow-postgres-storage
          persistentVolumeClaim:
            claimName: airflow-postgres-pvc
