{
 "title": "Monitoreo_auto",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Inferencias por Estado",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (status)(rate(inference_requests_total[1m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latencia Media",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(inference_request_latency_seconds_sum[1m]) / rate(inference_request_latency_seconds_count[1m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests de Inferencia",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(inference_requests_total)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}