apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: mlops-proyecto3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:10.4.1
        env:
          - name: GF_SECURITY_ADMIN_USER
            value: "admin"
          - name: GF_SECURITY_ADMIN_PASSWORD
            value: "admin"
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "true"
          - name: GF_USERS_ALLOW_SIGN_UP
            value: "false"
        ports:
          - containerPort: 3000
            name: web
        volumeMounts:
          - name: grafana-storage
            mountPath: /var/lib/grafana
          - name: config
            mountPath: /etc/grafana/provisioning/datasources/
          - name: dashboards-provider
            mountPath: /etc/grafana/provisioning/dashboards
          - name: dashboards-config
            mountPath: /var/lib/grafana/dashboards
      volumes:
        - name: grafana-storage
          emptyDir: {}
        - name: config
          configMap:
            name: grafana-datasources
        - name: dashboards-provider
          configMap:
            name: grafana-dashboard-provider
        - name: dashboards-config
          configMap:
            name: grafana-dashboard
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: mlops-proyecto3
spec:
  selector:
    app: grafana
  ports:
    - name: web
      port: 3000
      targetPort: 3000
  type: ClusterIP



