apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: mlops-proyecto3
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      # ---- Raspa la API de inferencia ----
      - job_name: inference-api
        metrics_path: /metrics
        static_configs:
          - targets: ['inference-api.mlops-proyecto3.svc.cluster.local:80']

      # ---- (Opcional) Raspa Prometheus a sí mismo ----
      - job_name: prometheus
        static_configs:
          - targets: ['prometheus.mlops-proyecto3.svc.cluster.local:9090']

